CREATE OR REPLACE VIEW VPI.VIEW_LAST_BATCH_LOG AS
SELECT
	LOG_TIME,
	BATCH_ID,
	PROGRESS_STEP,
	PROGRESS_DESC,
	SPENT_TIME
FROM
	VPI.VIEW_EXTRACT_BATCH_LOG
WHERE
	BATCH_ID	= (SELECT MAX(BATCH_ID) FROM VPI.EXTRACT_BATCH_LOG)

WITH READ ONLY;
