CREATE OR REPLACE VIEW VPI.VIEW_EXTRACT_GEN_CODE AS
SELECT
	INTERFACE_ID,
	UNION_VIEW,
	VPI.EXTRACT_UTILITY.GEN_EXTRACT_VIEW(INTERFACE_ID)	AS GEN_CODE
FROM
	VPI.EXTRACT_INTERFACE

WITH READ ONLY;
