CREATE OR REPLACE VIEW VPI.VIEW_GEN_RULE_VIEW_CODE AS
SELECT
	INTERFACE_ID,
	RULE_VIEW,
	VPI.EXTRACT_UTILITY.GEN_RULE_VIEW(INTERFACE_ID)	AS GEN_CODE
FROM
	VPI.EXTRACT_RULE_TAG_ALIAS
WHERE
	RULE_VIEW	IS NOT NULL

WITH READ ONLY;
