CREATE OR REPLACE VIEW VPI.VIEW_EXTRACT_METADATA AS
SELECT
	SERVICE_ID,
	SERVICE_NAME,
	SERVICE_OWNER,
	DESCRIPTION_,
	VPI.EXTRACT_DEPLOY.EXPORT_METADATA(SERVICE_ID)	AS METADATA_MANIFEST
FROM
	VPI.EXTRACT_SERVICE

WITH READ ONLY;
