CREATE TABLE VPI.EXTRACT_INTERFACE
(
	INTERFACE_ID	VARCHAR2(32)	NOT NULL,
	APP_ID			VARCHAR2(32)	NOT NULL,
	UNION_VIEW		VARCHAR2(64),
	SELECT_LIST		NVARCHAR2(1024),
	DESCRIPTION_	VARCHAR2(1024),

	CONSTRAINT PK_EXTRACT_INTERFACE PRIMARY KEY (INTERFACE_ID),
	CONSTRAINT CK_EXTRACT_INTERFACE_ID CHECK (INTERFACE_ID = UPPER(INTERFACE_ID)),
	CONSTRAINT FK_EXTRACT_INTERFACE_APP FOREIGN KEY (APP_ID) REFERENCES VPI.PRE_DEPLOY_APP (APP_ID)
)
STORAGE (INITIAL 16K NEXT 16K);

COMMENT ON COLUMN VPI.EXTRACT_INTERFACE.INTERFACE_ID
	IS 'The unique identifier for the interface, consider a naming convention within the enterprise.';
COMMENT ON COLUMN VPI.EXTRACT_INTERFACE.UNION_VIEW
	IS 'The name of view which will union all plug-ins under the same interface.';
COMMENT ON COLUMN VPI.EXTRACT_INTERFACE.SELECT_LIST
	IS 'The select list in the select statement, every plug-in view of the same interface will follow this signature.';
COMMENT ON COLUMN VPI.EXTRACT_INTERFACE.APP_ID
	IS 'The application of this interface.';
