CREATE TABLE VPI.EXTRACT_BATCH_LOG
(
	BATCH_ID		NUMBER(10)		NOT NULL,
	LOG_TIME		TIMESTAMP(3)	DEFAULT SYSTIMESTAMP	NOT NULL,
	PROGRESS_STEP	NUMBER(5)								NOT NULL,
	PROGRESS_DESC	VARCHAR2(128)
)	COMPRESS;

CREATE INDEX VPI.IX_EXTRACT_BATCH_LOG ON VPI.EXTRACT_BATCH_LOG (BATCH_ID, LOG_TIME, PROGRESS_STEP) COMPRESS;
