CREATE TABLE VPI.PRE_DEPLOY_VERSION
(
	APP_ID			VARCHAR2(32)			NOT NULL,
	APP_VER			NUMBER(4)				NOT NULL,
	COMMENT_		VARCHAR2(2000),
	DEPLOYED_DATE	DATE DEFAULT SYSDATE	NOT NULL,
	DEPLOYED_STATUS	VARCHAR2(16)			NOT NULL,

	CONSTRAINT PK_PRE_DEPLOY_VERSION PRIMARY KEY (APP_ID, APP_VER),
	CONSTRAINT FK_PRE_DEPLOY_VERSION FOREIGN KEY (APP_ID) REFERENCES VPI.PRE_DEPLOY_APP (APP_ID)
);

COMMENT ON TABLE VPI.PRE_DEPLOY_VERSION
	IS 'Version history of pre-deployment';
-- Add comments to the columns 
COMMENT ON COLUMN VPI.PRE_DEPLOY_VERSION.APP_ID
	IS 'Application ID.';
COMMENT ON COLUMN VPI.PRE_DEPLOY_VERSION.APP_VER
	IS 'Version number of the application.';
