CREATE TABLE VPI.PRE_DEPLOY_VERSION
(
	SERVICE_ID		VARCHAR2(32)			NOT NULL,
	VERSION_NUM		NUMBER(4)				NOT NULL,
	COMMENT_		VARCHAR2(2000),
	DEPLOYED_DATE	DATE DEFAULT SYSDATE	NOT NULL,
	DEPLOYED_STATUS	VARCHAR2(16)			NOT NULL,

	CONSTRAINT PK_PRE_DEPLOY_VERSION PRIMARY KEY (SERVICE_ID, VERSION_NUM),
	CONSTRAINT FK_PRE_DEPLOY_VERSION FOREIGN KEY (SERVICE_ID) REFERENCES VPI.EXTRACT_SERVICE (SERVICE_ID)
);

COMMENT ON TABLE VPI.PRE_DEPLOY_VERSION
	IS 'Version history of pre-deployment';
-- Add comments to the columns 
COMMENT ON COLUMN VPI.PRE_DEPLOY_VERSION.SERVICE_ID
	IS 'The extract service (application) ID.';
COMMENT ON COLUMN VPI.PRE_DEPLOY_VERSION.VERSION_NUM
	IS 'Version number of the extract service (application).';
