CREATE TABLE VPI.PRE_DEPLOY_SCRIPT
(
	SERVICE_ID		VARCHAR2(32)			NOT NULL,
	VERSION_NUM		NUMBER(4)				NOT NULL,
	OBJECT_NAME		VARCHAR2(61)			NOT NULL,
	OBJECT_TYPE		VARCHAR2(19)			NOT NULL,
	OBJECT_SCRIPT	CLOB					NOT NULL,
	IS_DEPLOYED		NUMBER(1) DEFAULT 0		NOT NULL,
	DEPLOYED_ERROR	VARCHAR2(512),

	CONSTRAINT PK_PRE_DEPLOY_SCRIPT PRIMARY KEY (SERVICE_ID, VERSION_NUM, OBJECT_NAME),
	CONSTRAINT FK_PRE_DEPLOY_SCRIPT FOREIGN KEY (SERVICE_ID, VERSION_NUM) REFERENCES VPI.PRE_DEPLOY_VERSION (SERVICE_ID, VERSION_NUM)
);
