CREATE OR REPLACE TRIGGER VPI.TRG_EXTRACT_INTERFACE
AFTER INSERT ON VPI.EXTRACT_INTERFACE
FOR EACH ROW
BEGIN
	INSERT INTO VPI.EXTRACT_RULE_TAG_ALIAS (INTERFACE_ID, RULE_VIEW)
	VALUES (:new.INTERFACE_ID,  UPPER(REGEXP_SUBSTR(:new.UNION_VIEW, '^[^.]+\.')) || 'VIEW_RULE_' || :new.INTERFACE_ID);
END;
/
